services:

  piatto:
    container_name: piatto
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    
    volumes:
      - ./src:/home/app/web/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    environment:
      - WORKERS=1
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE:-piatto}
      - DB_USER=${MYSQL_USER:-piatto}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8000:8080" # piatto app -> 80(00)
    env_file:
      - ./.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - postgres
    networks:
      - backend

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-piatto}
      MYSQL_USER: ${MYSQL_USER:-piatto}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - backend
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80" # phpMyAdmin -> 8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
