name: Build & Deploy Frontend to Cloud Run (prod)

on:
  push:
    branches:
      - prod
    paths:
      - "frontend/**"
      - ".github/workflows/prod-frontend-docker.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-frontend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-frontend-

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cloud-run-hackathon-475303

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and Push Docker Image (with cache)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            us-central1-docker.pkg.dev/cloud-run-hackathon-475303/frontend-repo/frontend:latest
            us-central1-docker.pkg.dev/cloud-run-hackathon-475303/frontend-repo/frontend:prod-${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy piatto-frontend \
            --image=us-central1-docker.pkg.dev/cloud-run-hackathon-475303/frontend-repo/frontend:prod-${{ github.sha }} \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --cpu=1 --memory=512Mi --min-instances=0 --max-instances=3
